// Extrait les cookies Instagram du browser local (Chrome, Brave, Arc, etc.)
// et les ecrit au format Netscape cookies.txt utilise par yt-dlp/gallery-dl.
//
// Usage :
//   deno run -A scripts/extract_browser_cookies.ts \
//     --profile "$HOME/Library/Application Support/Arc/User Data/Default" \
//     --keychain "Arc Safe Storage" \
//     --domain instagram.com \
//     --out .instagram-cookies.txt
//
// Pourquoi ce script et pas `yt-dlp --cookies-from-browser` : yt-dlp hardcode
// le nom de l'entree Keychain par browser (Chrome → "Chrome Safe Storage").
// Pour Arc, il faut "Arc Safe Storage" et il n'y a pas d'override CLI.
//
// Comment ca marche :
//   1. Lit la table `cookies` du SQLite `Cookies` du profil browser.
//   2. Recupere le mot de passe du Keychain via `security`.
//   3. Derive une clef AES-128 via PBKDF2-SHA1 (salt="saltysalt", iter=1003).
//   4. Dechiffre chaque encrypted_value en AES-128-CBC, IV=16 espaces.
//   5. Sur Chrome v10+, prefixe "v10" ou "v11" → strip les 3 premiers bytes.
//   6. Sur Chrome >= 80, decrypte commence par 32 bytes SHA256 du host →
//      heuristique : si le premier byte n'est pas imprimable, strip 32 bytes.
//   7. Filtre par domaine et ecrit au format Netscape.

import { Database } from "jsr:@db/sqlite@0.12";

const args = parseArgs(Deno.args);

const profilePath = args.profile;
const keychainEntry = args.keychain;
const domainFilter = args.domain;
const outPath = args.out;

if (!profilePath || !keychainEntry || !domainFilter || !outPath) {
  console.error("usage: --profile <path> --keychain <name> --domain <filter> --out <file>");
  Deno.exit(1);
}

// 1. Recupere le mot de passe du Keychain. -w → renvoie juste le password.
//    Declenche une prompt graphique si l'app n'a pas deja l'autorisation.
const sec = new Deno.Command("security", {
  args: ["find-generic-password", "-s", keychainEntry, "-w"],
  stdout: "piped",
  stderr: "piped",
});
const secRes = await sec.output();
if (secRes.code !== 0) {
  console.error("Keychain lookup failed:", new TextDecoder().decode(secRes.stderr));
  Deno.exit(1);
}
const password = new TextDecoder().decode(secRes.stdout).trim();

// 2. Derive la clef AES via PBKDF2 (Chrome utilise toujours les memes params).
const enc = new TextEncoder();
const pwKey = await crypto.subtle.importKey(
  "raw",
  enc.encode(password),
  { name: "PBKDF2" },
  false,
  ["deriveBits"],
);
const keyBits = await crypto.subtle.deriveBits(
  {
    name: "PBKDF2",
    salt: enc.encode("saltysalt"),
    iterations: 1003,
    hash: "SHA-1",
  },
  pwKey,
  128,
);
const aesKey = await crypto.subtle.importKey(
  "raw",
  keyBits,
  { name: "AES-CBC" },
  false,
  ["decrypt"],
);
const iv = new Uint8Array(16).fill(0x20); // 16 espaces

// 3. Lit la table cookies. Sur certains profils Chromium le fichier est
//    verrouille tant que le browser tourne — on copie d'abord vers /tmp.
const cookiesSrc = `${profilePath}/Cookies`;
const cookiesTmp = `/tmp/extract-cookies-${crypto.randomUUID()}.db`;
await Deno.copyFile(cookiesSrc, cookiesTmp);

const db = new Database(cookiesTmp, { readonly: true });
type Row = {
  host_key: string;
  name: string;
  value: string;
  encrypted_value: Uint8Array;
  path: string;
  expires_utc: number;
  is_secure: number;
};
const rows = db.prepare(
  `SELECT host_key, name, value, encrypted_value, path, expires_utc, is_secure
   FROM cookies WHERE host_key LIKE ?`,
).all<Row>(`%${domainFilter}%`);
db.close();
await Deno.remove(cookiesTmp);

// 4. Dechiffre chaque cookie et formate.
const out: string[] = [
  "# Netscape HTTP Cookie File",
  "# Generated by extract_browser_cookies.ts",
  "",
];
let ok = 0;
let failed = 0;

for (const r of rows) {
  let value = r.value;
  if (r.encrypted_value && r.encrypted_value.length > 0) {
    try {
      const buf = r.encrypted_value;
      const prefix = new TextDecoder().decode(buf.slice(0, 3));
      const ciphertext = (prefix === "v10" || prefix === "v11") ? buf.slice(3) : buf;
      const plainBuf = await crypto.subtle.decrypt(
        { name: "AES-CBC", iv },
        aesKey,
        ciphertext,
      );
      let plain = new Uint8Array(plainBuf);
      // Chrome >= 80 prefixe avec SHA256(host_key) (32 bytes). Heuristique :
      // si les 32 premiers bytes contiennent un byte non-imprimable et que
      // les bytes 32+ ressemblent a du texte, on strip.
      if (plain.length > 32) {
        const head = plain.slice(0, 32);
        const tail = plain.slice(32);
        const tailLooksText = tail.every((b) => b >= 0x09 && b < 0x7f);
        const headHasNonprint = Array.from(head).some((b) => b < 0x09 || (b >= 0x0e && b < 0x20));
        if (tailLooksText && headHasNonprint) plain = tail;
      }
      value = new TextDecoder().decode(plain);
      ok++;
    } catch (err) {
      failed++;
      console.warn(`decrypt failed for ${r.host_key} ${r.name}: ${(err as Error).message}`);
      continue;
    }
  }

  const domain = r.host_key;
  const domainFlag = domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = r.is_secure ? "TRUE" : "FALSE";
  // expires_utc : microsecondes depuis 1601-01-01.
  // - 0  → cookie de session (pas d'expiration explicite cote browser)
  // - <1e15 → date bidon (Chrome ecrit parfois des valeurs garbage). Sentinel.
  // - sinon → conversion vers Unix seconds.
  // Netscape format : 0 signifie "session cookie", yt-dlp l'accepte et garde
  // le cookie pour la duree de la requete.
  let expiresUnix = 0;
  if (r.expires_utc > 1_000_000_000_000_000) {
    const candidate = Math.floor((r.expires_utc - 11_644_473_600_000_000) / 1_000_000);
    if (candidate > 0) expiresUnix = candidate;
  }
  out.push([domain, domainFlag, r.path, secure, expiresUnix, r.name, value].join("\t"));
}

await Deno.writeTextFile(outPath, out.join("\n") + "\n");
console.log(`Extracted ${ok} cookies (${failed} failed) → ${outPath}`);

function parseArgs(argv: string[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith("--")) {
      out[argv[i].slice(2)] = argv[i + 1];
      i++;
    }
  }
  return out;
}
